# Default values for sonarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ullbergm/sonarr
  tag: latest
  pullPolicy: Always

ingress:
  host: sonarr.media.ullberg.family

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
