# Default values for nzbget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ullbergm/nzbget
  tag: latest
  pullPolicy: Always

ingress:
  host: nzbget.media.ullberg.family

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
