apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "embyserver.fullname" . }}
  labels:
    app: {{ template "embyserver.name" . }}
    chart: {{ template "embyserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "embyserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "EST5EDT"
          ports:
            - name: embyserver
              containerPort: 8096
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - hostPath:
            path: /data/config/embyserver
            type: DirectoryOrCreate
          name: config
        - hostPath:
            path: /data/media
            type: DirectoryOrCreate
          name: media
