apiVersion: v1
kind: Service
metadata:
  name: {{ template "embyserver.fullname" . }}
  labels:
    app: {{ template "embyserver.name" . }}
    chart: {{ template "embyserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
      name: embyserver
  selector:
    app: {{ template "embyserver.name" . }}
    release: {{ .Release.Name }}
